// ── FEATURE FLAGS ──────────────────────────────────────────────────────────
export const FLAGS = {
  weekNav: true,
  swipeGestures: true,
  haptics: true,
  springAnimations: true,
  toasts: true,
  skeletonLoading: true,
  ratings: true,
  nutritionDashboard: true,
  priceEstimates: true,
  prepCookSplit: true,
};

// ── CONSTANTS ──────────────────────────────────────────────────────────────
export const AISLES = {
  produce: { label: "🥬 Obst & Gemüse", order: 1 },
  dairy:   { label: "🧀 Käse & Milch",  order: 2 },
  meat:    { label: "🥩 Fleisch & Fisch", order: 3 },
  dry:     { label: "🥫 Trockenwaren",  order: 4 },
  bread:   { label: "🍞 Brot & Backwaren", order: 5 },
  spices:  { label: "🧄 Gewürze & Saucen", order: 6 },
  oils:    { label: "🫙 Öle & Essig",   order: 7 },
  other:   { label: "🛒 Sonstiges",     order: 8 },
};

export const AISLES_OPT = [
  ["produce","🥬 Gemüse"],["dairy","🧀 Milch"],["meat","🥩 Fleisch"],
  ["dry","🥫 Trocken"],["bread","🍞 Brot"],["spices","🧄 Gewürze"],
  ["oils","🫙 Öle"],["other","🛒 Sonstiges"],
];

// Extended SPICES map: HelloFresh → REWE equivalents
export const SPICES = {
  "gewürzmischung hello curry":       "Currypulver, Kurkuma & Kreuzkümmel",
  "gewürzmischung hello muskat":      "Muskatnuss, gemahlen",
  "gewürzmischung hello paprika":     "Paprikapulver edelsüß & Knoblauchpulver",
  "gewürzmischung hello mediterranee":"Kräuter der Provence",
  "gewürzmischung hello italiano":    "Oregano & Basilikum",
  "gewürzmischung hello smoky bbq":   "Paprika & Knoblauch Gewürzmischung",
  "gewürzmischung hello chinese":     "5-Gewürze-Pulver",
  "gewürzmischung hello mexican":     "Kreuzkümmel & Chili",
  "gewürzmischung hello garam masala":"Garam Masala",
  "gewürzmischung hello italian herb":"Oregano, getrocknet",
  "hello curry":   "Currypulver",
  "hello muskat":  "Muskatnuss, gemahlen",
  "hello paprika": "Paprikapulver edelsüß",
};

// Ingredient alias dictionary for normalisation
export const ING_ALIASES = {
  "balsamic-crème":          "Balsamicocreme",
  "balsamic crème":          "Balsamicocreme",
  "kochsahne leicht":        "Kochsahne",
  "sahne leicht":            "Kochsahne",
  "frühlingszwiebeln":       "Frühlingszwiebel",
  "knoblauch":               "Knoblauchzehe",
  "hartkäse (gerieben)":     "Hartkäse, gerieben",
};

// Split ingredients: source → [targets]
export const ING_SPLITS = {
  "petersilie glatt/thymian":          ["Petersilie", "Thymian"],
  "petersilie/schnittlauch":            ["Petersilie", "Schnittlauch"],
  "blumenkohlröschen & karotten":       ["Blumenkohlröschen", "Karotten"],
  "karotte-lauch-mix":                  ["Karotte", "Lauch"],
  "karotten-lauch-mix":                 ["Karotte", "Lauch"],
};

// REWE price estimates (normalised ingredient → € per typical pack)
export const REWE_PRICES = {
  "hähnchenbrustfilet":3.49,"lachsfilet":4.99,"schweineschnitzel":3.29,
  "hackfleischzubereitung vom weiderind":2.99,"rinderhackfleisch":3.49,
  "couscous":0.89,"jasminreis":0.99,"basmatireis":1.19,"nudeln":0.89,
  "kichererbsen":0.79,"linsen":0.89,"bohnen":0.69,
  "kartoffeln":1.29,"mehligkochende kartoffeln":1.29,"festkochende kartoffeln":1.29,
  "karotte":0.59,"karotten":0.59,"blumenkohlröschen":1.49,"brokkoli":0.99,
  "zucchini":0.89,"paprika":0.99,"spinat":1.29,"babyspinat":1.49,
  "tomaten":0.99,"cocktailtomaten":1.49,"cherrytomaten":1.49,
  "zwiebel":0.59,"rote zwiebel":0.79,"schalotte":0.89,
  "knoblauchzehe":0.59,"knoblauch":0.59,
  "feldsalat":1.29,"salatherz (romana)":1.29,"blattsalatmischung":1.29,
  "apfel":0.99,"zitrone":0.49,"orange":0.59,
  "camembert":1.99,"hirtenkäse leicht":2.49,"hartkäse, gerieben":1.89,
  "mozzarella":0.99,"sahnejoghurt":0.79,"naturjoghurt":0.69,
  "milch":0.89,"kochsahne":0.59,"frischkäse":0.99,
  "butter":1.79,"eier":2.29,"kräuterbutter":0.99,
  "semmelbrösel":0.59,"mehl":0.69,"paniermehl":0.69,
  "olivenöl":2.29,"trüffelöl":3.99,"balsamicocreme":1.99,"balsamico":1.29,
  "senf":0.69,"mittelscharfer senf":0.69,"dijonsenf":1.29,
  "mayonnaise":0.99,"ketchup":0.99,"sojasoße":0.99,
  "gemüsebrühpulver":0.89,"rinderbrühe":0.89,"hühnerbrühe":0.89,
  "wildpreiselbeerenmarmelade":1.49,"cranberries, getrocknet":1.29,
  "aprikosenchutney":1.89,"würziges zwiebel-chutney":1.49,
  "ravigote sauce":1.99,"curry":0.89,"currypulver":0.89,
  "paprikapulver":0.79,"muskatnuss, gemahlen":0.89,"kumin, gemahlen":0.89,
  "thymian":0.79,"petersilie":0.69,"schnittlauch":0.79,"rosmarin":0.79,
  "mini-fladenbrot":0.99,"fladenbrot":1.29,"ciabatta":1.29,"baguette":0.99,
  "radieschen":0.79,"frühlingszwiebel":0.69,"lauch":0.89,
  "reis":0.99,"spaghetti":0.89,"penne":0.89,
  "tahini":2.49,"hummus":1.49,"pesto":1.99,
  // pantry staples
  "salz":0.49,"pfeffer":0.79,"zucker":0.69,"öl":1.49,"honig":2.49,
  "wasser":0.00,"essig":0.89,"zitronensaft":0.59,
};

export const PROTEINS = {
  fish:       { emoji: "🐟", label: "Fisch",  color: "#e07b6a" },
  pork:       { emoji: "🥩", label: "Schwein", color: "#c8703a" },
  beef:       { emoji: "🐄", label: "Rind",   color: "#7a3010" },
  chicken:    { emoji: "🍗", label: "Huhn",   color: "#c8a83a" },
  vegetarian: { emoji: "🥗", label: "Veggie", color: "#4a7c59" },
};

export const DAYS = [
  { id: "mon", label: "Mo", labelEN: "Mon" },
  { id: "tue", label: "Di", labelEN: "Tue" },
  { id: "wed", label: "Mi", labelEN: "Wed" },
  { id: "thu", label: "Do", labelEN: "Thu" },
  { id: "fri", label: "Fr", labelEN: "Fri" },
  { id: "sat", label: "Sa", labelEN: "Sat" },
  { id: "sun", label: "So", labelEN: "Sun" },
];

// Ingredient name translations: German (lowercase) → English display name
export const ING_TRANS_EN = {
  "couscous": "Couscous",
  "kumin, gemahlen": "Cumin, ground",
  "gemüsebrühpulver": "Vegetable stock powder",
  "cranberries, getrocknet": "Cranberries, dried",
  "kichererbsen": "Chickpeas",
  "sahnejoghurt": "Cream yoghurt",
  "aprikosenchutney": "Apricot chutney",
  "blumenkohlröschen & karotten": "Cauliflower florets & carrots",
  "blumenkohlröschen": "Cauliflower florets",
  "babyspinat": "Baby spinach",
  "hirtenkäse leicht": "Light feta cheese",
  "hirtenkäse": "Feta cheese",
  "camembert": "Camembert",
  "mini-fladenbrot": "Mini flatbread",
  "fladenbrot": "Flatbread",
  "salatherz (romana)": "Romaine lettuce heart",
  "apfel": "Apple",
  "rote zwiebel": "Red onion",
  "würziges zwiebel-chutney": "Spicy onion chutney",
  "wildpreiselbeerenmarmelade": "Wild cranberry jam",
  "kräuterbutter": "Herb butter",
  "gewürzmischung hello curry": "Spice blend (curry)",
  "gewürzmischung hello paprika": "Spice blend (paprika)",
  "gewürzmischung hello italiano": "Spice blend (Italian herbs)",
  "hähnchenbrustfilet": "Chicken breast fillet",
  "hähnchenbrustfilet in lake": "Chicken breast fillet",
  "cocktailtomaten": "Cherry tomatoes",
  "cherrytomaten": "Cherry tomatoes",
  "frühlingszwiebel": "Spring onion",
  "naturjoghurt": "Natural yoghurt",
  "semmelbrösel": "Breadcrumbs",
  "paniermehl": "Breadcrumbs",
  "lachsfilet": "Salmon fillet",
  "mehligkochende kartoffeln": "Floury potatoes",
  "festkochende kartoffeln": "Waxy potatoes",
  "kartoffeln": "Potatoes",
  "feldsalat": "Lamb's lettuce",
  "orange": "Orange",
  "zitrone": "Lemon",
  "mittelscharfer senf": "Medium-hot mustard",
  "dijonsenf": "Dijon mustard",
  "senf": "Mustard",
  "trüffelöl": "Truffle oil",
  "ravigote sauce": "Ravigote sauce",
  "petersilie/schnittlauch": "Parsley/Chives",
  "petersilie": "Parsley",
  "schnittlauch": "Chives",
  "schweineschnitzel": "Pork schnitzel",
  "radieschen": "Radishes",
  "mayonnaise": "Mayonnaise",
  "blattsalatmischung": "Mixed leaf salad",
  "karotten": "Carrots",
  "karotte": "Carrot",
  "zwiebel": "Onion",
  "knoblauchzehe": "Garlic clove",
  "knoblauch": "Garlic",
  "spinat": "Spinach",
  "tomaten": "Tomatoes",
  "paprika": "Bell pepper",
  "zucchini": "Courgette",
  "brokkoli": "Broccoli",
  "lauch": "Leek",
  "milch": "Milk",
  "butter": "Butter",
  "eier": "Eggs",
  "mehl": "Flour",
  "zucker": "Sugar",
  "salz": "Salt",
  "pfeffer": "Pepper",
  "öl": "Oil",
  "olivenöl": "Olive oil",
  "wasser": "Water",
  "honig": "Honey",
  "essig": "Vinegar",
  "balsamicocreme": "Balsamic glaze",
  "balsamico": "Balsamic vinegar",
  "kochsahne": "Cooking cream",
  "frischkäse": "Cream cheese",
  "mozzarella": "Mozzarella",
  "hartkäse, gerieben": "Hard cheese, grated",
  "nudeln": "Pasta",
  "spaghetti": "Spaghetti",
  "penne": "Penne",
  "reis": "Rice",
  "basmatireis": "Basmati rice",
  "jasminreis": "Jasmine rice",
  "linsen": "Lentils",
  "bohnen": "Beans",
  "hummus": "Hummus",
  "tahini": "Tahini",
  "pesto": "Pesto",
  "sojasoße": "Soy sauce",
  "currypulver": "Curry powder",
  "paprikapulver": "Paprika powder",
  "muskatnuss, gemahlen": "Nutmeg, ground",
  "thymian": "Thyme",
  "rosmarin": "Rosemary",
  "oregano": "Oregano",
  "rinderhackfleisch": "Minced beef",
  "hackfleischzubereitung vom weiderind": "Minced beef",
  "ciabatta": "Ciabatta",
  "baguette": "Baguette",
};

export const SE = { none: "❌", partial: "⚠️", full: "✅" };
export const SL = { none: "Fehlt", partial: "Teilweise", full: "Vorhanden" };

export const EMOJIS = ["🍝","🍗","🥩","🐟","🥗","🍲","🌮","🌯","🍔","🥘","🍜","🫕","🥙","🍱","🥣","🧆"];

// ── SEED DATA ──────────────────────────────────────────────────────────────
export const SEED = [
  {key:"r1",order:1,emoji:"🥗",color:"#4a7c59",kcal:837,prepMins:10,cookMins:15,
   name:"Warmer Blumenkohl-Karotten-Salat mit Hirtenkäse",
   nameEN:"Warm Cauliflower & Carrot Salad with Feta",
   description:"Gebratener Blumenkohl und Karotten auf würzigem Couscous mit Kichererbsen, Babyspinat und cremigem Hirtenkäse.",
   descriptionEN:"Roasted cauliflower and carrots on spiced couscous with chickpeas, baby spinach and creamy feta cheese.",
   time:"15–25 min",difficulty:"Einfach",
   pantryItems:["Olivenöl","Wasser","Salz","Pfeffer"],
   ingredients:[
    {id:"r1_1",name:"Couscous",amount:"150g",aisle:"dry"},
    {id:"r1_2",name:"Kumin, gemahlen",amount:"1g",aisle:"spices"},
    {id:"r1_3",name:"Gemüsebrühpulver",amount:"4g",aisle:"spices"},
    {id:"r1_4",name:"Cranberries, getrocknet",amount:"20g",aisle:"dry"},
    {id:"r1_5",name:"Kichererbsen",amount:"390g",aisle:"dry"},
    {id:"r1_6",name:"Sahnejoghurt",amount:"100g",aisle:"dairy"},
    {id:"r1_7",name:"Aprikosenchutney",amount:"25g",aisle:"spices"},
    {id:"r1_8",name:"Blumenkohlröschen & Karotten",amount:"300g",aisle:"produce"},
    {id:"r1_9",name:"Gewürzmischung Hello Curry",amount:"2g",aisle:"spices"},
    {id:"r1_10",name:"Babyspinat",amount:"50g",aisle:"produce"},
    {id:"r1_11",name:"Hirtenkäse leicht",amount:"100g",aisle:"dairy"},
   ],instructions:[
    {step:1,title:"Gemüse anbraten",titleEN:"Sauté vegetables",text:"Bring water to a boil. Fry chickpeas, cauliflower florets and carrots in a large pan with olive oil. Add 50ml hot water, cover with a lid and steam for 4–5 minutes."},
    {step:2,title:"Couscous & Dressing",titleEN:"Couscous & Dressing",text:"Pour boiling water over couscous, vegetable stock powder, cranberries and cumin. Cover and let swell. Mix yogurt with Hello Curry, salt and pepper for the curry dip."},
    {step:3,title:"Anrichten",titleEN:"Plate up",text:"Mix vegetables, couscous and dip together. Fold in baby spinach. Crumble feta cheese over the top. Enjoy!"},
   ]},
  {key:"r2",order:2,emoji:"🧀",color:"#c8883a",kcal:919,prepMins:12,cookMins:12,
   name:"Fruchtiger Brot-Salat mit Ofen-Camembert",
   nameEN:"Fruity Bread Salad with Baked Camembert",
   description:"Knusprige Kräuterbutter-Croutons mit Apfel, karamellisierten roten Zwiebeln und Salatherz, dazu schmelzender Ofen-Camembert mit Preiselbeermarmelade.",
   descriptionEN:"Crispy herb butter croutons with apple, caramelised red onions and romaine lettuce, with melted baked camembert and cranberry jam.",
   time:"15–25 min",difficulty:"Einfach",
   pantryItems:["Salz","Pfeffer","Öl","Butter","Olivenöl","Wasser"],
   ingredients:[
    {id:"r2_1",name:"Camembert",amount:"250g",aisle:"dairy"},
    {id:"r2_2",name:"Mini-Fladenbrot",amount:"150g",aisle:"bread"},
    {id:"r2_3",name:"Salatherz (Romana)",amount:"120g",aisle:"produce"},
    {id:"r2_4",name:"Apfel",amount:"1 Stück",aisle:"produce"},
    {id:"r2_5",name:"Rote Zwiebel",amount:"2 Stück",aisle:"produce"},
    {id:"r2_6",name:"Würziges Zwiebel-Chutney",amount:"40g",aisle:"spices"},
    {id:"r2_7",name:"Wildpreiselbeerenmarmelade",amount:"25g",aisle:"spices"},
    {id:"r2_8",name:"Kräuterbutter",amount:"20g",aisle:"dairy"},
    {id:"r2_9",name:"Gewürzmischung Hello Paprika",amount:"2g",aisle:"spices"},
   ],instructions:[
    {step:1,title:"Vorbereiten",titleEN:"Prepare",text:"Preheat oven to 200°C. Halve the camembert and place cut side up in an oven dish. Score a crosshatch pattern, drizzle with oil and bake for 12–15 minutes."},
    {step:2,title:"Croutons",titleEN:"Croutons",text:"Slice flatbread and toast in a pan with herb butter until golden."},
    {step:3,title:"Salat",titleEN:"Salad",text:"Slice onions into thin rings and fry until caramelised. Mix with lettuce, apple slices and chutney. Add croutons. Serve with warm camembert and cranberry jam. Enjoy!"},
   ]},
  {key:"r3",order:3,emoji:"🍗",color:"#c8703a",kcal:736,prepMins:10,cookMins:20,
   name:"Knuspriges Hähnchen mit Couscous und Tomaten-Dip",
   nameEN:"Crispy Chicken with Couscous and Tomato Dip",
   description:"Goldenes, krustengebratenes Hähnchenbrustfilet auf fluffigem Couscous mit frischen Cocktailtomaten und cremigem Joghurt-Dip.",
   descriptionEN:"Golden crumbed chicken breast fillet on fluffy couscous with fresh cherry tomatoes and a creamy yoghurt dip.",
   time:"20–30 min",difficulty:"Einfach",
   pantryItems:["Olivenöl","Wasser","Salz","Pfeffer","Zucker"],
   ingredients:[
    {id:"r3_1",name:"Hähnchenbrustfilet",amount:"250g",aisle:"meat"},
    {id:"r3_2",name:"Couscous",amount:"100g",aisle:"dry"},
    {id:"r3_3",name:"Cocktailtomaten",amount:"150g",aisle:"produce"},
    {id:"r3_4",name:"Frühlingszwiebel",amount:"2 Stück",aisle:"produce"},
    {id:"r3_5",name:"Naturjoghurt",amount:"100g",aisle:"dairy"},
    {id:"r3_6",name:"Gemüsebrühpulver",amount:"4g",aisle:"spices"},
    {id:"r3_7",name:"Gewürzmischung Hello Italiano",amount:"2g",aisle:"spices"},
    {id:"r3_8",name:"Semmelbrösel",amount:"30g",aisle:"dry"},
   ],instructions:[
    {step:1,title:"Hähnchen vorbereiten",titleEN:"Prepare chicken",text:"Pound chicken flat. Mix breadcrumbs with Hello Italiano. Season chicken, coat in breadcrumbs and press firmly."},
    {step:2,title:"Braten",titleEN:"Pan fry",text:"Fry chicken in oil over medium heat for 4–5 minutes per side until golden and cooked through."},
    {step:3,title:"Couscous & Dip",titleEN:"Couscous & Dip",text:"Pour boiling stock water over couscous, cover and let swell 5 minutes. Halve tomatoes, slice spring onions. Mix yogurt with salt, pepper and a pinch of sugar. Serve together. Enjoy!"},
   ]},
  {key:"r4",order:4,emoji:"🐟",color:"#4a6c8a",kcal:842,prepMins:15,cookMins:20,
   name:"Lachs mit Kräuterkruste und Trüffelstampf",
   nameEN:"Herb-Crusted Salmon with Truffle Mash",
   description:"Saftiges Lachsfilet mit knuspriger Senf-Kräuter-Kruste auf samtigem Trüffelkartoffelstampf mit frischem Orangensalat.",
   descriptionEN:"Juicy salmon fillet with a crispy mustard and herb crust on a velvety truffle mash with a fresh orange salad.",
   time:"25–35 min",difficulty:"Mittel",
   pantryItems:["Olivenöl","Butter","Salz","Pfeffer","Milch","Honig"],
   ingredients:[
    {id:"r4_1",name:"Lachsfilet",amount:"250g",aisle:"meat"},
    {id:"r4_2",name:"Mehligkochende Kartoffeln",amount:"400g",aisle:"produce"},
    {id:"r4_3",name:"Feldsalat",amount:"50g",aisle:"produce"},
    {id:"r4_4",name:"Orange",amount:"1 Stück",aisle:"produce"},
    {id:"r4_5",name:"Zitrone",amount:"1 Stück",aisle:"produce"},
    {id:"r4_6",name:"Petersilie/Schnittlauch",amount:"10g",aisle:"produce"},
    {id:"r4_7",name:"Semmelbrösel",amount:"30g",aisle:"dry"},
    {id:"r4_8",name:"Mittelscharfer Senf",amount:"15g",aisle:"spices"},
    {id:"r4_9",name:"Trüffelöl",amount:"10ml",aisle:"oils"},
    {id:"r4_10",name:"Gemüsebrühpulver",amount:"4g",aisle:"spices"},
    {id:"r4_11",name:"Ravigote Sauce",amount:"40g",aisle:"spices"},
   ],instructions:[
    {step:1,title:"Kartoffeln kochen",titleEN:"Boil potatoes",text:"Preheat oven to 200°C. Peel, cube and boil potatoes in salted water for 12–14 minutes. Drain."},
    {step:2,title:"Lachs-Kruste",titleEN:"Herb crust",text:"Grate lemon zest. Mix butter with breadcrumbs, ¾ of the herbs, mustard, lemon zest, salt and pepper. Press onto salmon fillets. Bake 18–20 minutes, grill function last 3 minutes."},
    {step:3,title:"Orangensalat",titleEN:"Orange salad",text:"Peel and slice orange. Mix orange juice, lemon juice, honey, olive oil, mustard, salt and pepper as dressing. Toss with lamb's lettuce."},
    {step:4,title:"Trüffelstampf & Anrichten",titleEN:"Truffle mash & plate",text:"Mash potatoes with truffle oil, stock, milk and butter. Plate salmon, salad and mash. Serve with Ravigote sauce. Enjoy!"},
   ]},
  {key:"r5",order:5,emoji:"🥩",color:"#6b7c3f",kcal:803,prepMins:15,cookMins:25,
   name:"Knuspriges Kräuterschnitzel dazu Ofenkartoffeln",
   nameEN:"Crispy Herb Schnitzel with Oven Potatoes",
   description:"Saftiges Schweineschnitzel in goldener Kräuter-Panierung mit knusprigen Ofenkartoffeln und frischem Blattsalat mit Radieschen.",
   descriptionEN:"Juicy pork schnitzel in a golden herb crumb with crispy oven potatoes and a fresh leaf salad with radishes.",
   time:"30–40 min",difficulty:"Einfach",
   pantryItems:["Pfeffer","Zucker","Öl","Eier","Salz","Mehl"],
   ingredients:[
    {id:"r5_1",name:"Schweineschnitzel",amount:"250g",aisle:"meat"},
    {id:"r5_2",name:"Radieschen",amount:"100g",aisle:"produce"},
    {id:"r5_3",name:"Petersilie/Schnittlauch",amount:"10g",aisle:"produce"},
    {id:"r5_4",name:"Naturjoghurt",amount:"75g",aisle:"dairy"},
    {id:"r5_5",name:"Zitrone",amount:"1 Stück",aisle:"produce"},
    {id:"r5_6",name:"Mayonnaise",amount:"25g",aisle:"spices"},
    {id:"r5_7",name:"Semmelbrösel",amount:"50g",aisle:"dry"},
    {id:"r5_8",name:"Gewürzmischung Hello Paprika",amount:"2g",aisle:"spices"},
    {id:"r5_9",name:"Festkochende Kartoffeln",amount:"400g",aisle:"produce"},
    {id:"r5_10",name:"Blattsalatmischung",amount:"50g",aisle:"produce"},
   ],instructions:[
    {step:1,title:"Kartoffeln backen",titleEN:"Oven potatoes",text:"Preheat oven to 220°C. Cut potatoes lengthwise into wedges. Mix with oil, Hello Paprika, salt and pepper. Bake for 25 minutes."},
    {step:2,title:"Schnitzel panieren",titleEN:"Bread schnitzel",text:"Chop herbs and mix with breadcrumbs. Flour (plate 1), egg (plate 2), herb crumbs (plate 3). Season schnitzel, coat in flour, dip in egg, press in crumbs."},
    {step:3,title:"Dressing & Salat",titleEN:"Dressing & salad",text:"Mix yoghurt, mayonnaise, lemon juice, salt, pepper and a pinch of sugar. Slice radishes. Mix with leaf salad."},
    {step:4,title:"Schnitzel braten & Anrichten",titleEN:"Fry & plate",text:"Heat 100ml oil in pan. Fry schnitzel 5–7 minutes per side, basting with oil. Drain on kitchen paper. Serve with potatoes, salad and lemon wedges. Enjoy!"},
   ]},
];
